server:
  port: 8080
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: hmdp
  datasource:
    driver-class-name: ${hm-dianping.datasource.driver-class-name}
    url: jdbc:mysql://${hm-dianping.datasource.host}:${hm-dianping.datasource.port}/${hm-dianping.datasource.database}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${hm-dianping.datasource.username}
    password: ${hm-dianping.datasource.password}
  data:
    redis:
      host: ${hm-dianping.data.redis.host}
      port: ${hm-dianping.data.redis.port}
      password: ${hm-dianping.data.redis.password}
      database: ${hm-dianping.data.redis.database}
      lettuce:
        pool:
          max-active: ${hm-dianping.data.redis.lettuce.pool.max-active}
          max-wait: ${hm-dianping.data.redis.lettuce.pool.max-wait}
          max-idle: ${hm-dianping.data.redis.lettuce.pool.max-idle}
          min-idle: ${hm-dianping.data.redis.lettuce.pool.min-idle}

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug